<?php
return array (
  'site' => 'http://localhost/wzz',
  'sharesite' => 'localhost/wzz',
  'ti' => '30',
  'p1' => '',
  'pp' => '',
  'song' => '0.5',
  'openreg' => '1',
  'sitename' => '暴风赚钱',
  'kou_pr' => '10',
  'kou_day' => '5',
  'kou_hour' => '1,2,3,7,20',
  'yunpian' => '',
  'safe' => '1',
  'qqkf' => '28343613',
  'tc' => '20',
  'iphour' => '',
  'fangwen' => '3',
  'area' => '全国',
  'city' => '地区',
  'weixin_reg' => '1',
  'daysong' => '0.02',
  'ipreg2' => '1',
  'reg_yzr1' => '0.5',
  'gotimes' => '',
  'AdminLoginCode' => '1',
  'AdminEmail' => '',
  'UserAddArticle' => '1',
  'UserAddArticleType' => '31,搞笑,0.01',
  'DetailMoreNum' => '',
  'DetailPvOpen' => '',
);
?>